# Generated by Django 3.1.6 on 2021-04-18 06:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('pcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('status1', models.CharField(default='not', max_length=20)),
                ('status2', models.CharField(default='pending', max_length=20)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('sdate', models.DateField(default=datetime.datetime.now)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='login.user')),
                ('payid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.payment')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sid', to='login.user')),
            ],
        ),
    ]
