# Generated by Django 3.1.6 on 2021-04-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.payment'),
        ),
    ]
