# Generated by Django 3.1.6 on 2021-04-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210418_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payid',
        ),
    ]
