# Generated by Django 3.1.6 on 2021-04-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('bname', models.CharField(default='none', max_length=50)),
                ('qty', models.CharField(max_length=10)),
                ('pd', models.TextField(max_length=500)),
                ('p_pic', models.ImageField(upload_to='images')),
                ('cprice', models.IntegerField()),
                ('sprice', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
